### ISSUE TITLE
What is AdjClose for in Ohlc class?

### ISSUE THREAD

**Issue by Transigent** [anilca/NetTrader.Indicator#1]
Hi, firstly thanks for this project, I think it will be very useful. 

I have been trying to understand what AdjClose is for in the Ohlc class, in the context of MACD. I have been looking at the sample data file table.csv, which has 
Date | Open | High | Low | Close | Volume | Adj Close

All the candle data available on exchanges seems to have all fields except AdjClose, yet your source data includes it. 

a) Are we supposed to supply something in the AdjClose column or just Close, or both? What is the difference?
b) AdjClose and Close are within about 20% of each other in the csv file, before Calculate(). But after macd.Calculate(),  the macd.OhlcList has had all the Close values replaced: 
Before:  152.2
After:   -1.827068
Is there a reason for this we need to know about?

Thanks for any clarification.

**Comment by anilca** [comment]
Hi,

Here you can find a detailed explanation of adjusted closing price:
[https://www.investopedia.com/terms/a/adjusted_closing_price.asp](url)

As you can see in the MACD class the AdjClose column is not used, so supplying just the Close column is enough.
