### ISSUE TITLE
Getting Signal

### ISSUE THREAD

**Issue by EhsanGhanbari** [anilca/NetTrader.Indicator#17]
Hi, How can I use the result of the Calculate method of the Indicators to get a signal (Buy, Sell, or stay) !? what are those numbers in the result and what they mean? thanks

**Comment by coolmarat** [comment]
Getting signals from indicator is your own logic resonsibility. Try to google for crossover moving average strategy. So indicators give you a value and your strategy then interprete it as a signal to buy or sell.
