### ISSUE TITLE
Örnek proje

### ISSUE THREAD

**Issue by redquantum** [anilca/NetTrader.Indicator#2]
Merhaba,

İndicator kullanımı ile ilgili elinizde paylaşabileceğiniz örnek bir proje var mıdır?
Konuyu yeni öğrendiğim için nasıl uygulanacağı hakkında bilgi toplamaya çalışıyorum.

Teşekkür ederim.

**Comment by anilca** [comment]
Test projesinde her indicatorun nasıl cagirilacagini gösteren metotlar bulabilirsiniz.
