### ISSUE TITLE
Ohlc Date: Opening or Closing?

### ISSUE THREAD

**Issue by paulsiersma** [anilca/NetTrader.Indicator#21]
Hi there. First of all, thanks for creating this awesome package and saving me from a lot of icky math!

I have a question (that might be somewhat stupid): Should the `Date` property of the `Ohlc` class correspond to the  Open Time of the candle, or the close time?

I think it should be the Closing Time of the candle period, but I just wanted to be sure. Thanks for your reply!

**Comment by anilca** [comment]
Think of that the data is daily and each line is containing the opening, closing, highest and lowest price for that specific day. The candles actually don't store opening or closing time information. A candle should contain o (open), h (high), l (low), c (close) information for a specific time interval.
