### ISSUE TITLE
RSI not working correctly.

### ISSUE THREAD

**Issue by Stephengower** [anilca/NetTrader.Indicator#4]
Hi, I'm quite sure the RSI indicator isn't calculating properly. You're not using the Period correctly.  You're using a "change" List that you keep adding to for the full history.  I think you're calculating the average gain and average loss for the full period, instead of the period variable.  When I ran the 14 day RSI for the full SPY historical data, your RSI was always calculating to be around 50. It's supposed to be an oscillator from 1-100.   Anyway, thanks for the API.  

I'm not totally sure my revisions are correct, but here's what I did to work around the problem.  

`   public override RSISerie Calculate()
        {
            RSISerie rsiSerie = new RSISerie();

            // Add null values for first item, iteration will start from second item of OhlcList
            rsiSerie.RS.Add(null);
            rsiSerie.RSI.Add(null);
          //  change.Add(null);

            for (int i = 1; i < OhlcList.Count; i++)
            {
                if (i > this.Period)
                {
                    int start = i - Period;
                    double gainSum = 0;
                    for(int j= start; j <= i; j++)
                    {
                        double thisChange = OhlcList[j].Close - OhlcList[j - 1].Close;
                        if (thisChange > 0)
                        {
                            gainSum = gainSum + thisChange;
                        }
                    }
                    var averageGain = gainSum / Period;
                    double lossSum = 0;
                    for (int j = start; j <= i; j++)
                    {
                        double thisChange = OhlcList[j].Close - OhlcList[j - 1].Close;
                        if (thisChange < 0)
                        {
                            lossSum = lossSum + thisChange;
                        }
                    }
                    var averageLoss = -1 * lossSum / Period;
                    //   var averageGain = change.Where(x => x > 0).Sum() / change.Count;
                   // var averageLoss = change.Where(x => x < 0).Sum() * (-1) / change.Count;
                    var rs = averageGain / averageLoss;
                    rsiSerie.RS.Add(rs);
                    var rsi = 100 - (100 / (1 + rs));
                    Console.WriteLine("i=" + i + " averageGai=" + averageGain + " averageLoss=" + averageLoss + " rs=" + rs+ " rsi="+ rsi);
                    rsiSerie.RSI.Add(rsi);
                    // assign change for item
                 //   change.Add(OhlcList[i].Close - OhlcList[i - 1].Close);
                }
                else
                {   
                    rsiSerie.RS.Add(null);
                    rsiSerie.RSI.Add(null);
                    // assign change for item
                  //  change.Add(OhlcList[i].Close - OhlcList[i - 1].Close);
                }
            }
            return rsiSerie;
        }
    }`

**Comment by muteddisk** [comment]
RSI is definitely not working properly. Everything else I tested was bang on.

**Comment by muteddisk** [comment]
> Hi, I'm quite sure the RSI indicator isn't calculating properly. You're not using the Period correctly. You're using a "change" List that you keep adding to for the full history. I think you're calculating the average gain and average loss for the full period, instead of the period variable. When I ran the 14 day RSI for the full SPY historical data, your RSI was always calculating to be around 50. It's supposed to be an oscillator from 1-100. Anyway, thanks for the API.
> 
> I'm not totally sure my revisions are correct, but here's what I did to work around the problem.
> 
> ` public override RSISerie Calculate()
> {
> RSISerie rsiSerie = new RSISerie();
> 
> ```
>         // Add null values for first item, iteration will start from second item of OhlcList
>         rsiSerie.RS.Add(null);
>         rsiSerie.RSI.Add(null);
>       //  change.Add(null);
> 
>         for (int i = 1; i < OhlcList.Count; i++)
>         {
>             if (i > this.Period)
>             {
>                 int start = i - Period;
>                 double gainSum = 0;
>                 for(int j= start; j <= i; j++)
>                 {
>                     double thisChange = OhlcList[j].Close - OhlcList[j - 1].Close;
>                     if (thisChange > 0)
>                     {
>                         gainSum = gainSum + thisChange;
>                     }
>                 }
>                 var averageGain = gainSum / Period;
>                 double lossSum = 0;
>                 for (int j = start; j <= i; j++)
>                 {
>                     double thisChange = OhlcList[j].Close - OhlcList[j - 1].Close;
>                     if (thisChange < 0)
>                     {
>                         lossSum = lossSum + thisChange;
>                     }
>                 }
>                 var averageLoss = -1 * lossSum / Period;
>                 //   var averageGain = change.Where(x => x > 0).Sum() / change.Count;
>                // var averageLoss = change.Where(x => x < 0).Sum() * (-1) / change.Count;
>                 var rs = averageGain / averageLoss;
>                 rsiSerie.RS.Add(rs);
>                 var rsi = 100 - (100 / (1 + rs));
>                 Console.WriteLine("i=" + i + " averageGai=" + averageGain + " averageLoss=" + averageLoss + " rs=" + rs+ " rsi="+ rsi);
>                 rsiSerie.RSI.Add(rsi);
>                 // assign change for item
>              //   change.Add(OhlcList[i].Close - OhlcList[i - 1].Close);
>             }
>             else
>             {   
>                 rsiSerie.RS.Add(null);
>                 rsiSerie.RSI.Add(null);
>                 // assign change for item
>               //  change.Add(OhlcList[i].Close - OhlcList[i - 1].Close);
>             }
>         }
>         return rsiSerie;
>     }
> }`
> ```

The numbers look better with your code but for some reason when I throw in data from Binance....I'm not getting the same value as Binance does.

**Comment by Stephengower** [comment]
Interesting. I can't check into this right now, but please let me know if you find a way to make them match (It may be the code I submitted isn't perfect).

**Comment by muteddisk** [comment]
> Hi, I'm quite sure the RSI indicator isn't calculating properly. You're not using the Period correctly. You're using a "change" List that you keep adding to for the full history. I think you're calculating the average gain and average loss for the full period, instead of the period variable. When I ran the 14 day RSI for the full SPY historical data, your RSI was always calculating to be around 50. It's supposed to be an oscillator from 1-100. Anyway, thanks for the API.
> 
> I'm not totally sure my revisions are correct, but here's what I did to work around the problem.
> 
> ` public override RSISerie Calculate()
> {
> RSISerie rsiSerie = new RSISerie();
> 
> ```
>         // Add null values for first item, iteration will start from second item of OhlcList
>         rsiSerie.RS.Add(null);
>         rsiSerie.RSI.Add(null);
>       //  change.Add(null);
> 
>         for (int i = 1; i < OhlcList.Count; i++)
>         {
>             if (i > this.Period)
>             {
>                 int start = i - Period;
>                 double gainSum = 0;
>                 for(int j= start; j <= i; j++)
>                 {
>                     double thisChange = OhlcList[j].Close - OhlcList[j - 1].Close;
>                     if (thisChange > 0)
>                     {
>                         gainSum = gainSum + thisChange;
>                     }
>                 }
>                 var averageGain = gainSum / Period;
>                 double lossSum = 0;
>                 for (int j = start; j <= i; j++)
>                 {
>                     double thisChange = OhlcList[j].Close - OhlcList[j - 1].Close;
>                     if (thisChange < 0)
>                     {
>                         lossSum = lossSum + thisChange;
>                     }
>                 }
>                 var averageLoss = -1 * lossSum / Period;
>                 //   var averageGain = change.Where(x => x > 0).Sum() / change.Count;
>                // var averageLoss = change.Where(x => x < 0).Sum() * (-1) / change.Count;
>                 var rs = averageGain / averageLoss;
>                 rsiSerie.RS.Add(rs);
>                 var rsi = 100 - (100 / (1 + rs));
>                 Console.WriteLine("i=" + i + " averageGai=" + averageGain + " averageLoss=" + averageLoss + " rs=" + rs+ " rsi="+ rsi);
>                 rsiSerie.RSI.Add(rsi);
>                 // assign change for item
>              //   change.Add(OhlcList[i].Close - OhlcList[i - 1].Close);
>             }
>             else
>             {   
>                 rsiSerie.RS.Add(null);
>                 rsiSerie.RSI.Add(null);
>                 // assign change for item
>               //  change.Add(OhlcList[i].Close - OhlcList[i - 1].Close);
>             }
>         }
>         return rsiSerie;
>     }
> }`
> ```

Your code is right. Good stuff.

**Comment by Stephengower** [comment]
Oh good.  Before I thought you had posted a message saying my code didn't quite match what you were expecting.  This isn't a place for chatting, but I'm curious about what you're working on.   Are you starting a new project?

**Comment by muteddisk** [comment]
> Oh good. Before I thought you had posted a message saying my code didn't quite match what you were expecting. This isn't a place for chatting, but I'm curious about what you're working on. Are you starting a new project?

I did. I updated it like 5 times. then I realized I was taking the closing price of the previous kline instead of the opening price. From there everything lined up.

thanks for the great work

**Comment by anilca** [comment]
Hi @Stephengower,

So sorry for the late response. Seems like you are right, I pushed directly your script. Thanks for helping out.

**Comment by Stephengower** [comment]
Ok, great. thanks.  I'm happy I could help.
