### ISSUE TITLE
Bollinger Bands source set as HLC3

### ISSUE THREAD

**Issue by leftweb** [anilca/NetTrader.Indicator#5]
I have been battling why the calculated Bollinger Band values do not match those from the exchanges I use with the default settings.

Line 49 assumes source is HLC3:

`OhlcList[i].Close = (OhlcList[i].High + OhlcList[i].Low + OhlcList[i].Close) / 3;`

TradingView, for example, uses Close by default.

Perhaps the BollingerBand override could also support Close as a parameter.

For now, I plan to proceed with line 49 commented out.

Thanks

**Comment by anilca** [comment]
Hi @leftweb,
In the source code you can find the reference and the formula being used to calculate Bollinger Bands. And of course you can clone and update the source code like what ever you want.
