### ISSUE TITLE
RSI is Off

### ISSUE THREAD

**Issue by cbaxi** [anilca/NetTrader.Indicator#7]
You should be using formula described here..

https://stackoverflow.com/questions/38481354/rsi-vs-wilders-rsi-calculation-problems

Answer by RooiWillie in this thread matches ditto! Copying here..

=====================================================================

In order to calculate the RSI, you need a period to calculate it with. As noted on Wikipedia, 14 is used quite often.

So the calculation steps would be as follows:

Period 1 - 13, RSI = 0

Period 14:

AverageGain = TotalGain / PeriodCount;
AverageLoss = TotalLoss / PeriodCount;
RS = AverageGain / AverageLoss;
RSI = 100 - 100 / (1 + RS);
Period 15 - to period (N):

if (Period(N)Change > 0
  AverageGain(N) = ((AverageGain(N - 1) * (PeriodCount - 1)) + Period(N)Change) / PeriodCount;
else
  AverageGain(N) = (AverageGain(N - 1) * (PeriodCount - 1)) / PeriodCount;

if (this.Change < 0)
  AverageLoss(N) = ((AverageLoss(N - 1) * (PeriodCount - 1)) + Math.Abs(Period(N)Change)) / PeriodCount;
else
  AverageLoss(N) = (AverageLoss(N - 1) * (PeriodCount - 1)) / PeriodCount;

RS = AverageGain / AverageLoss;
RSI = 100 - (100 / (1 + RS));

**Comment by gugavaro** [comment]
I notice the same thing, RSI values are not returning the expected results when I test it.

**Comment by anilca** [comment]
Resolved by #12
