### ISSUE TITLE
Modify SMA to work on fields other than Close

### ISSUE THREAD

**Issue by FrankRay78** [anilca/NetTrader.Indicator#8]
Firstly, really great library and thanks for sharing. 

Small comment.  The SMA is currently hard coded to use the Close field.  It would be good for it to be able to work on other fields, Volume perhaps being most common. 

        public override SingleDoubleSerie Calculate()
        {
            SingleDoubleSerie smaSerie = new SingleDoubleSerie();
                
            for (int i = 0; i < OhlcList.Count; i++)
            {   
                if (i >= Period - 1)
                {
                    double sum = 0;
                    for (int j = i; j >= i - (Period - 1); j--)
                    {
                        sum += OhlcList[j].Close;
                    }
                    double avg = sum / Period;
                    smaSerie.Values.Add(avg);
                }
                else
                {
                    smaSerie.Values.Add(null);
                }
            }

            return smaSerie;
        }

I might have a go at implementing more flexability regarding the field it uses if I get a chance...

**Comment by anilca** [comment]
Hi, 
Merged #14 for adding ability to SMA, EMA, WMA, DEMA and ZLEMA to work on fields other than Close. Thanks for your suggestion.

**Comment by FrankRay78** [comment]
Very cool, thanks for implementing this.  I didn't have time but it's a really good improvement / addition to your already excellent codebase.
